Remove quiet logger test
LogErrorToStdout was removed in [1: 9937d22]

1: 9937d2282a50ae3530a2fee4523a2dbf6a495547
   Fix AttributeError: 'LogErrorToStdout' object has no attribute 'info' (#112)